import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NewTask from "../components/tasks/NewTask";
import { TasksList } from "@components/tasks/TasksList";
import { useEffect, useState } from "react";
import { useIndexedDb } from "@hooks/useIndexedDb";
import { DB_TODOS_NAME, DB_TODOS_STORE_NAME } from "@constants/db";
import { TaskFromDB } from "../types/db";

export default function Home() {
  const db = useIndexedDb(DB_TODOS_NAME, DB_TODOS_STORE_NAME);

  const [fetch, setFetch] = useState<boolean>(true);
  const [tasks, setTasks] = useState<TaskFromDB[]>([]);

  useEffect(() => {
    if (db) {
      const tasksFromDB: TaskFromDB[] = [];
      const cursor = db.transaction(DB_TODOS_NAME, "readwrite").objectStore(DB_TODOS_STORE_NAME).openCursor();
      cursor.onsuccess = (event) => {
        const { result } = event.target as IDBRequest<IDBCursorWithValue>;

        if (result) {
          tasksFromDB.push(result.value);
          result.continue();
        } else {
          setTasks(tasksFromDB);
          setFetch(false)
        }
      };

      cursor.onerror = (event) => {
        console.error(event);
      }
    }
  }, [db, fetch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NewTask onAdd={() => setFetch(true)} db={db} />
        <TasksList tasks={tasks} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
